defaults:
  - generator: hifi_generator
  - mel_generator: text_to_mel
  - datasets: custom_dataset
  - dataloader: ljspeech_specs_generation
  - transforms: empty
  - _self_
device: 'cpu'
audio_to_mel:
  _target_: src.model.AudioToMelSpectrogram
checkpoint_path: 'saved/generator-checkpoint-epoch70.pth'
path_to_save: 'generated_audio'
