_target_: src.model.HiFiGenerator
in_channels: 80
out_channels: 128
conv_transpose_kernels: [16, 16, 4, 4]
upsample_rates: [8, 8, 2, 2]
mrf_kernels: [3, 7, 11]
mrf_dilation_config: [
  [[1, 1], [3, 1], [5, 1]],
  [[1, 1], [3, 1], [5, 1]],
  [[1, 1], [3, 1], [5, 1]],
]
